### ISSUE TITLE
Removing Variable Spindle to Compile for Arduino Nano

### ISSUE THREAD

**Issue by eakinsj96** [UnfinishedBusiness/XmotionFirmware#3]
I have disabled Variable Spindle in order to get the size down to compile for arduino nano. 
I have not yet tested but suspect it to work because a plasma cnc does not have a spindle. 
I have also created a schematic based on what i can gather going through the code. 
Please correct me if i am wrong. 
![image](https://user-images.githubusercontent.com/66133161/92505496-2b4b4200-f1d2-11ea-8160-2454c57ff822.png)

**Comment by UnfinishedBusiness** [comment]
Everything looks good. I'm assuming you are going to interface with a machine that doesn't have a 50:1 voltage divider built-in and you plan to measure the raw arc voltage? If that's how you are doing it and your plasma machine is a pilot arc type, make sure to clamp the voltage at A0 with a TVS or Schottky diode to ensure that the analog input doesn't see all the huge transient voltage spikes involved with striking the arc. If your machine is an HF start, you're gonna have some experimenting to do because I don't have experience with dealing with the HV/HF arc that's emitted with basically an automotive coil that's fired at 60-100Hz...

That code can definitely be removed since the main focus is plasma only. Feel free to submit a pull request, It would be nice to have nano support...

Also, when you wire your control box, make sure that the Arduino and Laptop/Computer grounds/0V Ref  (which will be connected to each other via the USB port) are separated from the ground/0V ref of your power supply and stepper drivers. That will ensure that the noisy switching of the stepper phases and the electrical interference from the plasma arc itself doesn't interfere with the sensitive low-voltage control signals produced from the Nano. If the grounding is correct in the control box and you experience control resets or communication redundancy check failures randomly or occasionally, that's an indication that the power earth ground at the control box is more than 20 Ohms and I recommend running a dedicated earth ground rod 8FT deep with 4 Gauge wire or bigger to the machine connected as close as possible to the control box. When the earth ground starts to get much over 20 Ohms is when it becomes inefficient at draining the HF noise quickly enough and the result is a such a noisy power ground that it will radiate into your SGND plane (even though they are isolated) that the Nano will be operating on and will cause issues.

Let me know if you need any help down the line.

Thanks,
Travis
